FROM debian:stable-slim

# Create directory
RUN mkdir -p /presence
WORKDIR /presence

# Install and update packages
RUN apt-get update && apt-get install -y \
  bash \
  bc \
  bluetooth \
  bluez \
  bluez-hcidump \
  ca-certificates \
  curl \
  git \
  libmosquitto-dev \
  libwebsockets-dev \
  mosquitto \
  mosquitto-clients

# Copy and change script permissions
COPY presence.sh .
RUN chmod +x presence.sh

# Run
ENTRYPOINT ["/bin/bash"]
CMD ["/presence/presence.sh", "-p", "/config"]
